import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { encryptApiKey, decryptApiKey } from "@/lib/ai/crypto";
import { providerFor } from "@/lib/ai/providers";
const Body=z.object({provider:z.enum(["gemini","openai","anthropic"]),model:z.string().min(1).max(200),models:z.array(z.string().min(1).max(200)).max(30).default([]),apiKey:z.string().min(8).max(1000).optional(),enabled:z.boolean(),employeeEnabled:z.boolean(),managerEnabled:z.boolean(),adminEnabled:z.boolean(),monthlyRequestLimit:z.number().int().positive().nullable(),monthlyTokenLimit:z.number().int().positive().nullable()});
async function ctx(){const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)return null;const {data:p}=await s.from("profiles").select("id,company_id,role").eq("id",user.id).single();if(!p?.company_id||!["owner","admin"].includes(p.role))return null;return {s,p};}
export async function GET(){const c=await ctx();if(!c)return NextResponse.json({error:"Forbidden"},{status:403});const {data}=await c.s.from("ai_settings").select("enabled,provider,model,model_options,key_hint,employee_enabled,manager_enabled,admin_enabled,monthly_request_limit,monthly_token_limit,updated_at").eq("company_id",c.p.company_id).maybeSingle();return NextResponse.json({settings:data||null});}
export async function PUT(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Forbidden"},{status:403});const b=Body.parse(await req.json());const row:any={company_id:c.p.company_id,enabled:b.enabled,provider:b.provider,model:b.model,model_options:b.models,employee_enabled:b.employeeEnabled,manager_enabled:b.managerEnabled,admin_enabled:b.adminEnabled,monthly_request_limit:b.monthlyRequestLimit,monthly_token_limit:b.monthlyTokenLimit,updated_by:c.p.id,updated_at:new Date().toISOString()};if(b.apiKey){const e=encryptApiKey(b.apiKey);Object.assign(row,{api_key_ciphertext:e.ciphertext,api_key_iv:e.iv,api_key_tag:e.tag,key_hint:e.hint});}const {error}=await c.s.from("ai_settings").upsert(row);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true});}
export async function DELETE(){const c=await ctx();if(!c)return NextResponse.json({error:"Forbidden"},{status:403});const {error}=await c.s.from("ai_settings").update({api_key_ciphertext:null,api_key_iv:null,api_key_tag:null,key_hint:null,updated_by:c.p.id,updated_at:new Date().toISOString()}).eq("company_id",c.p.company_id);return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({ok:true});}
export async function POST(){const c=await ctx();if(!c)return NextResponse.json({error:"Forbidden"},{status:403});const {data:x}=await c.s.from("ai_settings").select("provider,model,api_key_ciphertext,api_key_iv,api_key_tag").eq("company_id",c.p.company_id).single();if(!x?.api_key_ciphertext||!x.provider||!x.model)return NextResponse.json({error:"Save a provider, model and API key first."},{status:400});try{const key=decryptApiKey(x.api_key_ciphertext,x.api_key_iv,x.api_key_tag);await providerFor(x.provider,key).complete({model:x.model,system:"Reply with OK only.",messages:[{role:"user",content:"Connection test"}],tools:[],timeoutMs:12000});return NextResponse.json({ok:true});}catch(e:any){return NextResponse.json({error:e?.message||"Connection failed"},{status:400});}}
