"use client";
import { useEffect,useState } from "react"; import { KeyRound,Loader2,ShieldCheck,Trash2 } from "lucide-react";
const providers=[["gemini","Google Gemini"],["openai","OpenAI"],["anthropic","Anthropic Claude"]] as const;
export default function AIAssistantSettings(){
 const [f,setF]=useState<any>({provider:"gemini",model:"",models:[],apiKey:"",enabled:false,employeeEnabled:true,managerEnabled:true,adminEnabled:true,monthlyRequestLimit:1000,monthlyTokenLimit:null,keyHint:null});const [busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[users,setUsers]=useState<any[]>([]),[overrides,setOverrides]=useState<Record<string,boolean>>({});
 useEffect(()=>{fetch("/api/ai/access").then(r=>r.json()).then(x=>{setUsers(x.users||[]);setOverrides(Object.fromEntries((x.overrides||[]).map((o:any)=>[o.user_id,o.enabled]))) });fetch("/api/ai/settings").then(r=>r.json()).then(x=>{const s=x.settings;if(s)setF((p:any)=>({...p,provider:s.provider||"gemini",model:s.model||"",models:Array.isArray(s.model_options)?s.model_options:[],enabled:s.enabled,employeeEnabled:s.employee_enabled,managerEnabled:s.manager_enabled,adminEnabled:s.admin_enabled,monthlyRequestLimit:s.monthly_request_limit,monthlyTokenLimit:s.monthly_token_limit,keyHint:s.key_hint}))})},[]);
 const save=async()=>{setBusy(true);setMsg("");const r=await fetch("/api/ai/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...f,models:f.models.filter(Boolean),apiKey:f.apiKey||undefined,monthlyRequestLimit:f.monthlyRequestLimit?Number(f.monthlyRequestLimit):null,monthlyTokenLimit:f.monthlyTokenLimit?Number(f.monthlyTokenLimit):null})});const j=await r.json();setBusy(false);setMsg(r.ok?"AI Assistant settings saved.":j.error||"Could not save.");if(r.ok&&f.apiKey)setF((p:any)=>({...p,apiKey:"",keyHint:"••••"+p.apiKey.slice(-4)}));};
 const test=async()=>{setBusy(true);setMsg("");const r=await fetch("/api/ai/settings",{method:"POST"});const j=await r.json();setBusy(false);setMsg(r.ok?"Connection successful.":j.error||"Connection failed.");};
 const setUser=async(id:string,value:string)=>{const enabled=value==="default"?null:value==="on";await fetch("/api/ai/access",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({userId:id,enabled})});setOverrides((p:any)=>{const n={...p};if(enabled===null)delete n[id];else n[id]=enabled;return n})};
 const del=async()=>{if(!confirm("Delete the saved AI provider key?"))return;const r=await fetch("/api/ai/settings",{method:"DELETE"});if(r.ok){setF((p:any)=>({...p,keyHint:null,apiKey:""}));setMsg("API key deleted.");}};
 return <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start gap-3"><div className="rounded-xl bg-brand-50 p-2.5 text-brand-700 dark:bg-brand-500/10 dark:text-brand-300"><KeyRound className="h-5 w-5"/></div><div><h2 className="font-semibold text-slate-900 dark:text-white">AI Assistant</h2><p className="mt-1 text-sm text-slate-500">Configure SM Assistant for this organization. HRMS data is sent to the AI provider selected here.</p></div></div>
 <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Provider<select value={f.provider} onChange={e=>setF({...f,provider:e.target.value})} className="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950">{providers.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-sm font-medium">Model<input value={f.model} list="ai-models" onChange={e=>setF({...f,model:e.target.value})} placeholder="Enter or choose a model" className="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"/><datalist id="ai-models">{(f.models||[]).map((m:string)=><option key={m} value={m}/>)}</datalist></label></div>
 <label className="mt-4 block text-sm font-medium">Editable model list<textarea value={(f.models||[]).join("\n")} onChange={e=>setF({...f,models:e.target.value.split("\n")})} rows={3} placeholder={"One model per line\nNo model names are hard-coded"} className="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"/></label>
 <label className="mt-4 block text-sm font-medium">API key <span className="font-normal text-slate-400">{f.keyHint?"Saved: "+f.keyHint:"No key saved"}</span><input type="password" value={f.apiKey} onChange={e=>setF({...f,apiKey:e.target.value})} placeholder={f.keyHint?"Paste a new key to rotate":"Paste API key"} autoComplete="new-password" className="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"/></label>
 <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Monthly request limit<input type="number" min="1" value={f.monthlyRequestLimit??""} onChange={e=>setF({...f,monthlyRequestLimit:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950"/></label><label className="text-sm">Monthly token limit (optional)<input type="number" min="1" value={f.monthlyTokenLimit??""} onChange={e=>setF({...f,monthlyTokenLimit:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950"/></label></div>
 <div className="mt-5 grid gap-2 sm:grid-cols-4">{[["enabled","Organization"],["employeeEnabled","Employee"],["managerEnabled","Manager"],["adminEnabled","Admin / Owner"]].map(([k,l])=><label key={k} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm dark:border-slate-700"><input type="checkbox" checked={!!f[k]} onChange={e=>setF({...f,[k]:e.target.checked})}/>{l}</label>)}</div>
 <div className="mt-5"><h3 className="text-sm font-semibold">Per-user override</h3><p className="mt-1 text-xs text-slate-500">Default follows the role setting above.</p><div className="mt-2 max-h-56 overflow-y-auto rounded-xl border border-slate-200 dark:border-slate-700">{users.map((u:any)=><div key={u.id} className="flex items-center gap-3 border-b border-slate-100 px-3 py-2 last:border-0 dark:border-slate-800"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{u.full_name}</p><p className="text-[11px] text-slate-400">{u.employee_code||u.role} · {u.role}</p></div><select value={overrides[u.id]===undefined?"default":overrides[u.id]?"on":"off"} onChange={e=>setUser(u.id,e.target.value)} className="rounded-lg border border-slate-300 bg-white px-2 py-1.5 text-xs dark:border-slate-700 dark:bg-slate-950"><option value="default">Role default</option><option value="on">Enabled</option><option value="off">Disabled</option></select></div>)}</div></div>
 <div className="mt-5 flex flex-wrap gap-2"><button onClick={save} disabled={busy} className="rounded-lg bg-brand-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:"Save settings"}</button><button onClick={test} disabled={busy||!f.keyHint} className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold dark:border-slate-700">Test connection</button>{f.keyHint&&<button onClick={del} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 px-3 py-2.5 text-sm text-rose-700 dark:border-rose-900"><Trash2 className="h-4 w-4"/>Delete key</button>}</div>{msg&&<p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{msg}</p>}<p className="mt-4 flex gap-2 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600 dark:bg-slate-950 dark:text-slate-300"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/>The API key is encrypted server-side with AES-256-GCM and is never returned to the browser or Android app. Do not paste keys into chat.</p></section>
}