"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { PageHeader } from "@/components/ui";
import { ShieldCheck, Building2, Users, Paperclip, MessageSquare, ListChecks, History, Save, Loader2 } from "lucide-react";
import { toast } from "@/components/Dialogs";

type Scope="company"|"department"|"employee";
type Policy={
 id?:string;company_id:string;scope_type:Scope;department_id?:string|null;employee_id?:string|null;
 status_pending_enabled:boolean;status_in_progress_enabled:boolean;status_hold_enabled:boolean;status_complete_enabled:boolean;
 can_create_task:boolean;can_delegate_task:boolean;can_reassign_task:boolean;can_edit_due_date:boolean;can_edit_priority:boolean;can_reopen_completed_task:boolean;
 comments_enabled:boolean;completion_comment_required:boolean;checklist_enabled:boolean;checklist_edit_allowed:boolean;checklist_required_for_completion:boolean;
 attachments_enabled:boolean;attachment_during_work_allowed:boolean;attachment_on_completion_allowed:boolean;attachment_required_for_completion:boolean;attachment_download_allowed:boolean;
 max_attachment_size_mb:number;allowed_attachment_types:string[];history_visibility:"own"|"assigned"|"department"|"company";activity_history_enabled:boolean;history_default_months:number;
};
const defaults=(company_id:string,scope_type:Scope):Policy=>({company_id,scope_type,department_id:null,employee_id:null,status_pending_enabled:true,status_in_progress_enabled:true,status_hold_enabled:true,status_complete_enabled:true,can_create_task:true,can_delegate_task:true,can_reassign_task:false,can_edit_due_date:false,can_edit_priority:false,can_reopen_completed_task:false,comments_enabled:true,completion_comment_required:false,checklist_enabled:true,checklist_edit_allowed:true,checklist_required_for_completion:false,attachments_enabled:true,attachment_during_work_allowed:true,attachment_on_completion_allowed:true,attachment_required_for_completion:false,attachment_download_allowed:true,max_attachment_size_mb:10,allowed_attachment_types:["pdf","jpg","jpeg","png","doc","docx","xls","xlsx"],history_visibility:"own",activity_history_enabled:true,history_default_months:1});
const Toggle=({label,desc,value,onChange}:{label:string;desc?:string;value:boolean;onChange:(v:boolean)=>void})=><label className="flex items-start justify-between gap-4 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><span><span className="block text-sm font-medium text-slate-900 dark:text-white">{label}</span>{desc&&<span className="mt-0.5 block text-xs text-slate-500">{desc}</span>}</span><button type="button" onClick={()=>onChange(!value)} className={`relative mt-0.5 h-6 w-11 shrink-0 rounded-full transition ${value?"bg-brand-600":"bg-slate-300 dark:bg-slate-600"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition-all ${value?"left-6":"left-1"}`}/></button></label>;
export default function TaskConfigurationPage(){
 const supabase=useMemo(()=>createClient(),[]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[companyId,setCompanyId]=useState("");const[scope,setScope]=useState<Scope>("company");const[target,setTarget]=useState("");const[depts,setDepts]=useState<any[]>([]);const[members,setMembers]=useState<any[]>([]);const[policies,setPolicies]=useState<Policy[]>([]);const[policy,setPolicy]=useState<Policy|null>(null);
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:p}=await supabase.from("profiles").select("company_id,role").eq("id",user.id).single();if(!p?.company_id)return;setCompanyId(p.company_id);const[{data:d},{data:m},{data:ps}]=await Promise.all([supabase.from("departments").select("id,name").eq("company_id",p.company_id).order("name"),supabase.from("profiles").select("id,full_name,department_id,role").eq("company_id",p.company_id).eq("status","active").order("full_name"),supabase.from("task_management_policies").select("*").eq("company_id",p.company_id)]);setDepts(d||[]);setMembers(m||[]);setPolicies((ps||[]) as Policy[]);setLoading(false)})()},[supabase]);
 useEffect(()=>{if(!companyId)return;let hit:Policy|undefined;if(scope==="company")hit=policies.find(x=>x.scope_type==="company");if(scope==="department"&&target)hit=policies.find(x=>x.scope_type==="department"&&x.department_id===target);if(scope==="employee"&&target)hit=policies.find(x=>x.scope_type==="employee"&&x.employee_id===target);const base=hit?{...hit}:defaults(companyId,scope);base.scope_type=scope;base.department_id=scope==="department"?target:null;base.employee_id=scope==="employee"?target:null;setPolicy(base)},[companyId,scope,target,policies]);
 const set=(k:keyof Policy,v:any)=>setPolicy(p=>p?{...p,[k]:v}:p);
 const save=async()=>{if(!policy)return;if(scope!=="company"&&!target)return toast("Select a target first.");setSaving(true);const payload={...policy,updated_by:(await supabase.auth.getUser()).data.user?.id};delete payload.id;let q=policy.id?supabase.from("task_management_policies").update(payload).eq("id",policy.id):supabase.from("task_management_policies").insert({...payload,created_by:payload.updated_by}).select().single();const{data,error}=await q;setSaving(false);if(error)return toast(error.message);toast("Task policy saved.");const{data:ps}=await supabase.from("task_management_policies").select("*").eq("company_id",companyId);setPolicies((ps||[]) as Policy[])};
 if(loading||!policy)return <div className="grid min-h-[45vh] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-brand-600"/></div>;
 const tabs=[["company","Company Default",Building2],["department","Department Rules",Users],["employee","Employee Rules",ShieldCheck]] as const;
 return <><PageHeader title="Task Management Configuration" subtitle="Control task workflow, status options, attachments and completion rules by company, department or employee."/>
 <div className="mb-5 grid gap-3 sm:grid-cols-3">{tabs.map(([k,l,I])=><button key={k} onClick={()=>{setScope(k);setTarget("")}} className={`flex items-center gap-3 rounded-2xl border p-4 text-left transition ${scope===k?"border-brand-500 bg-brand-50 text-brand-800 dark:bg-brand-500/10":"border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800"}`}><I className="h-5 w-5"/><span><b className="block text-sm">{l}</b><span className="text-xs opacity-70">{k==="company"?"Default for everyone":k==="department"?"Override a department":"Override one employee"}</span></span></button>)}</div>
 {scope!=="company"&&<div className="mb-5 rounded-2xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><label className="mb-2 block text-xs font-semibold uppercase tracking-wide text-slate-500">Select {scope}</label><select value={target} onChange={e=>setTarget(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="">Choose {scope}...</option>{(scope==="department"?depts:members).map((x:any)=><option key={x.id} value={x.id}>{x.name||x.full_name}</option>)}</select><p className="mt-2 text-xs text-slate-500">When an override exists, it takes priority over the company default for this {scope}.</p></div>}
 <div className="grid gap-5 xl:grid-cols-2">
 <section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h2 className="mb-4 flex items-center gap-2 font-semibold"><ListChecks className="h-4 w-4"/>Status & task actions</h2><div className="space-y-2"><Toggle label="Pending" value={policy.status_pending_enabled} onChange={v=>set("status_pending_enabled",v)}/><Toggle label="In Progress" value={policy.status_in_progress_enabled} onChange={v=>set("status_in_progress_enabled",v)}/><Toggle label="Hold" value={policy.status_hold_enabled} onChange={v=>set("status_hold_enabled",v)}/><Toggle label="Complete" value={policy.status_complete_enabled} onChange={v=>set("status_complete_enabled",v)}/><Toggle label="Create tasks" value={policy.can_create_task} onChange={v=>set("can_create_task",v)}/><Toggle label="Delegate tasks" value={policy.can_delegate_task} onChange={v=>set("can_delegate_task",v)}/><Toggle label="Reassign tasks" value={policy.can_reassign_task} onChange={v=>set("can_reassign_task",v)}/><Toggle label="Re-open completed tasks" value={policy.can_reopen_completed_task} onChange={v=>set("can_reopen_completed_task",v)}/><Toggle label="Edit due date" value={policy.can_edit_due_date} onChange={v=>set("can_edit_due_date",v)}/><Toggle label="Edit priority" value={policy.can_edit_priority} onChange={v=>set("can_edit_priority",v)}/></div></section>
 <section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h2 className="mb-4 flex items-center gap-2 font-semibold"><Paperclip className="h-4 w-4"/>Attachments</h2><div className="space-y-2"><Toggle label="Enable attachments" desc="Hide all attachment UI when disabled." value={policy.attachments_enabled} onChange={v=>set("attachments_enabled",v)}/><Toggle label="Upload while working" value={policy.attachment_during_work_allowed} onChange={v=>set("attachment_during_work_allowed",v)}/><Toggle label="Upload during completion" value={policy.attachment_on_completion_allowed} onChange={v=>set("attachment_on_completion_allowed",v)}/><Toggle label="Attachment required to complete" value={policy.attachment_required_for_completion} onChange={v=>set("attachment_required_for_completion",v)}/><Toggle label="Allow attachment download" value={policy.attachment_download_allowed} onChange={v=>set("attachment_download_allowed",v)}/><div className="grid grid-cols-2 gap-3 pt-2"><label className="text-xs font-medium text-slate-600">Max size (MB)<input type="number" min={1} max={100} value={policy.max_attachment_size_mb} onChange={e=>set("max_attachment_size_mb",Number(e.target.value))} className="mt-1 w-full rounded-lg border px-3 py-2 dark:border-slate-700 dark:bg-slate-900"/></label><label className="text-xs font-medium text-slate-600">Allowed extensions<input value={policy.allowed_attachment_types.join(", ")} onChange={e=>set("allowed_attachment_types",e.target.value.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean))} className="mt-1 w-full rounded-lg border px-3 py-2 dark:border-slate-700 dark:bg-slate-900"/></label></div></div></section>
 <section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h2 className="mb-4 flex items-center gap-2 font-semibold"><MessageSquare className="h-4 w-4"/>Comments & completion</h2><div className="space-y-2"><Toggle label="Enable comments" value={policy.comments_enabled} onChange={v=>set("comments_enabled",v)}/><Toggle label="Completion comment required" value={policy.completion_comment_required} onChange={v=>set("completion_comment_required",v)}/><Toggle label="Enable checklist / subtasks" value={policy.checklist_enabled} onChange={v=>set("checklist_enabled",v)}/><Toggle label="Allow checklist editing" value={policy.checklist_edit_allowed} onChange={v=>set("checklist_edit_allowed",v)}/><Toggle label="Checklist must be 100% complete" value={policy.checklist_required_for_completion} onChange={v=>set("checklist_required_for_completion",v)}/></div></section>
 <section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h2 className="mb-4 flex items-center gap-2 font-semibold"><History className="h-4 w-4"/>History & visibility</h2><div className="space-y-3"><Toggle label="Activity history" desc="Status, comments, uploads and checklist actions." value={policy.activity_history_enabled} onChange={v=>set("activity_history_enabled",v)}/><label className="block text-xs font-medium text-slate-600">History visibility<select value={policy.history_visibility} onChange={e=>set("history_visibility",e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 dark:border-slate-700 dark:bg-slate-900"><option value="own">Own tasks only</option><option value="assigned">Own + assigned tasks</option><option value="department">Department</option><option value="company">Whole company</option></select></label><label className="block text-xs font-medium text-slate-600">Default completed history<input type="number" min={1} max={24} value={policy.history_default_months} onChange={e=>set("history_default_months",Number(e.target.value))} className="mt-1 w-full rounded-lg border px-3 py-2 dark:border-slate-700 dark:bg-slate-900"/><span className="mt-1 block text-[11px] text-slate-400">months (UI will default to current month)</span></label></div></section>
 </div>
 <div className="sticky bottom-4 mt-6 flex justify-end"><button onClick={save} disabled={saving||(scope!=="company"&&!target)} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white shadow-lg disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save task policy</button></div></>}