import { NextResponse } from "next/server";import { friendlyError } from "@/lib/errors";
import { createClient } from "@/lib/supabase/server";
import { validateActionPayload } from "@/lib/ai/write-tools";
export async function POST(req:Request){
 const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:"Not authenticated"},{status:401});
 const {actionId,decision}=await req.json();if(!["confirm","cancel"].includes(decision))return NextResponse.json({error:"Invalid decision"},{status:400});
 const {data:a}=await s.from("ai_pending_actions").select("*").eq("id",actionId).eq("user_id",user.id).maybeSingle();if(!a||a.status!=="pending")return NextResponse.json({error:"Action is no longer pending."},{status:409});
 if(new Date(a.expires_at).getTime()<Date.now()){await s.from("ai_pending_actions").update({status:"expired"}).eq("id",a.id);return NextResponse.json({error:"This confirmation expired. Ask SM Assistant to prepare it again."},{status:410})}
 if(decision==="cancel"){await s.from("ai_pending_actions").update({status:"cancelled"}).eq("id",a.id);return NextResponse.json({ok:true,status:"cancelled"})}
 const {data:p}=await s.from("profiles").select("id,company_id,role,status").eq("id",user.id).single();if(!p||p.status!=="active"||p.company_id!==a.company_id||!["owner","admin","manager"].includes(p.role))return NextResponse.json({error:"Permission denied"},{status:403});
 // Claim the action atomically so a double tap / two tabs cannot execute it twice.
 const {data:claimed}=await s.from("ai_pending_actions").update({status:"confirmed",confirmed_at:new Date().toISOString()}).eq("id",a.id).eq("user_id",user.id).eq("status","pending").select("id").maybeSingle();
 if(!claimed)return NextResponse.json({error:"Action is no longer pending."},{status:409});
 try{
  a.payload=validateActionPayload(a.action,a.payload);
  let targetId=a.target_id;
  if(a.action==="assign_task"){const x=a.payload;const {data:e}=await s.from("profiles").select("id,manager_id").eq("id",x.employee_id).eq("company_id",p.company_id).eq("status","active").maybeSingle();if(!e||(p.role==="manager"&&e.id!==p.id&&e.manager_id!==p.id))throw new Error("Employee is outside your authorized team.");const {data:t,error}=await s.from("delegations").insert({company_id:p.company_id,title:x.title,description:x.description||"",assigned_to:x.employee_id,assigned_by:p.id,priority:x.priority||"medium",due_date:x.due_date,due_time:x.due_time||null}).select("id").single();if(error)throw error;targetId=t.id;await s.from("notifications").insert({company_id:p.company_id,user_id:x.employee_id,title:"New task delegated to you",body:`${x.title} · due ${x.due_date}${x.due_time?" "+x.due_time:""}`,kind:"task",link:"/tasks"})}
  else if(a.action==="update_task_due"){const x=a.payload;let q=s.from("delegations").update({due_date:x.due_date,due_time:x.due_time||null}).eq("id",x.task_id).eq("company_id",p.company_id);if(p.role==="manager")q=q.eq("assigned_by",p.id);const {data,error}=await q.select("id,assigned_to,title").maybeSingle();if(error||!data)throw error||new Error("Task is outside your authorized scope.");targetId=data.id;await s.from("notifications").insert({company_id:p.company_id,user_id:data.assigned_to,title:"Task due date updated",body:`${data.title} · new due ${x.due_date}${x.due_time?" "+x.due_time:""}`,kind:"task",link:"/tasks"})}
  else if(a.action==="raise_support_ticket"){const x=a.payload||{};if(!x.subject)throw new Error("Ticket subject is required.");const {data:t,error}=await s.from("tickets").insert({company_id:p.company_id,raised_by:p.id,subject:String(x.subject).slice(0,200),description:String(x.description||""),category:x.category||"general",priority:x.priority||"medium",source:"ai",ai_summary:x.ai_summary||null,meeting_required:!!x.meeting_required}).select("id,ticket_no").single();if(error)throw error;targetId=t.id;const {data:admins}=await s.from("profiles").select("id").eq("company_id",p.company_id).eq("status","active").in("role",["owner","admin"]);if(admins?.length)await s.from("notifications").insert(admins.map((u:any)=>({company_id:p.company_id,user_id:u.id,title:`New AI support ticket #${t.ticket_no}`,body:String(x.subject).slice(0,120),kind:"ticket",link:"/helpdesk"})));}
  else if(a.action==="request_support_meeting"){const x=a.payload||{};const start=new Date(x.starts_at);if(Number.isNaN(start.getTime()))throw new Error("A valid meeting date and time is required.");const end=x.ends_at?new Date(x.ends_at):new Date(start.getTime()+30*60000);if(end<=start)throw new Error("Meeting end time must be after start time.");const parts=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Kolkata",weekday:"short",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(start);const val=(t:string)=>parts.find(z=>z.type===t)?.value||"";if(val("weekday")==="Sun")throw new Error("Support meetings are not available on Sunday.");const sh=Number(val("hour")),sm=Number(val("minute"));const ep=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Kolkata",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(end);const ev=(t:string)=>ep.find(z=>z.type===t)?.value||"";const eh=Number(ev("hour")),em=Number(ev("minute"));if(sh<10||(eh>19)||(eh===19&&em>0)||sh>19||(sh===19&&sm>0))throw new Error("Support meetings can be booked only between 10:00 AM and 7:00 PM IST.");const {data:conflict}=await s.from("support_meetings").select("id").lt("starts_at",end.toISOString()).gt("ends_at",start.toISOString()).not("status","in","(cancelled,completed)").limit(1);if(conflict?.length)throw new Error("This time slot is already booked. Please choose another available time.");const {data:m,error}=await s.from("support_meetings").insert({company_id:p.company_id,ticket_id:x.ticket_id||null,requested_by:p.id,title:String(x.title||"SM HRMS support meeting").slice(0,200),description:String(x.description||""),starts_at:start.toISOString(),ends_at:end.toISOString(),timezone:"Asia/Kolkata",status:"requested",attendee_email:x.attendee_email||null,attendee_name:x.attendee_name||null}).select("id").single();if(error)throw error;targetId=m.id;}
  else throw new Error("Unsupported action.");
  await s.from("ai_pending_actions").update({status:"executed",confirmed_at:new Date().toISOString(),executed_at:new Date().toISOString(),target_id:targetId}).eq("id",a.id);
  await s.from("ai_action_log").insert({company_id:p.company_id,user_id:p.id,action:a.action,target_type:a.target_type,target_id:targetId,payload:a.payload,status:"executed"});
  return NextResponse.json({ok:true,status:"executed",message:"Action completed successfully."});
 }catch(e:any){await s.from("ai_pending_actions").update({status:"failed",confirmed_at:new Date().toISOString()}).eq("id",a.id);await s.from("ai_action_log").insert({company_id:a.company_id,user_id:user.id,action:a.action,target_type:a.target_type,target_id:a.target_id,payload:a.payload,status:"failed"});console.error("[ai/actions]",e);return NextResponse.json({error:friendlyError(e,"complete this action")},{status:400})}
}